Use the JS .toLowerCase() rather than .lower() which doesn't exist
Avoids this error on measure pages:
`Uncaught TypeError: t.trim(...).lower is not a function`