Update Selenium test element finders
This updates the Selenium tests to use a standard `find_element` method instead of our custom `wait_for_element` method.

The main advantage of this is that the failure error messages change from the cryptic:

```
selenium.common.exceptions.TimeoutException: Message: <selenium.webdriver.support.expected_conditions.presence_of_element_located object at 0x10631d828>
```

to a more helpful:

```
E       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Add measure"}
```

...which should speed up debugging.